### ISSUE TITLE
font height wrong in Windows

### ISSUE THREAD

**Issue by eyala-stratoscale** [DragonsInn/fontgen-loader#24]
I generated a font from svg files , it works perfectly on all linux computers and Mac, however it doesn't work on any windows browser.
Chrome Explorer and Firefox all act the same. When I look in browser network I see that the generated font is created with a huge line height between rows, In the browser I have to align every item that uses the font with vertical align: top to make it visible. When you inspect element each <i> with the font the height of that element is the height of the whole font file, about 240px. 
I can't get to the bottom of it, tried switching between ttf woff result is the same.

**Comment by Tuch** [comment]
@eyala-stratoscale could you say how u resolved it?

**Comment by eyala-stratoscale** [comment]
@Tuch what I had is one of the SVG heights was bigger in the svg size attributes itself. 
I edited that specific svg and made sure all other svg sizes are the same.
It's a workaround ...
