### ISSUE TITLE
Optional hash

### ISSUE THREAD

**Issue by Spitefulliar** [DragonsInn/fontgen-loader#3]
Hello, 
could you please make hash in the names of font files optional?

**Comment by IngwiePhoenix** [comment]
Sure. I’ll change that in a little. :)

**Comment by Spitefulliar** [comment]
Thanks! :)

**Comment by IngwiePhoenix** [comment]
Done. Preparing a commit. :)

**Comment by IngwiePhoenix** [comment]
Let me know if it works the way you want! :)

**Comment by Spitefulliar** [comment]
Thank you! I looked through the commit. And that's exactly what I meant. I hope to test it soon :)

**Comment by IngwiePhoenix** [comment]
I'm glad you like! Let me know when you tested.

**Comment by Spitefulliar** [comment]
Tested it. Works nice and smoothly .)

**Comment by IngwiePhoenix** [comment]
Great, glad to hear! ^_^
