### ISSUE TITLE
Generic error if SVG file cannot be converted

### ISSUE THREAD

**Issue by ha7ilm** [DragonsInn/fontgen-loader#35]
I wanted to convert a custom icon I've created in Inkscape, but I've got an error like this:

```
ERROR in ./~/css-loader!./~/fontgen-loader!./my.font.json
Module build failed: 
 @ ./my.font.json 4:14-118
 @ ./frontend.jsx
```

I did not understand what was the problem, because the error message did not include any further description (is it a problem with the config, the code or the files). 

Later I figured out that the SVG used some Inkscape specific features. To fix that:
* I created an SVG document in Inkscape with a size of (768, 1024) px. 
* converted every object to path, 
* saved the SVG file and edited it in a text editor. The result was like one of the files over here: `test/octicons/svg`. Only a `<path />` in an `<svg></svg>`.

After that, the font was successfully built.

**Comment by jeerbl** [comment]
So, what is the issue again?

**Comment by jeerbl** [comment]
Btw, I took over the project as this one was not being updated anymore.

New project is [here](https://github.com/jeerbl/webfonts-loader).

Thx
Jerome

**Comment by ha7ilm** [comment]
This is a very minor issue. It took me some time to find out that the build failed because the SVG was not the right format. An error like `Module build failed: invalid SVG format` or `webfonts-generator failed` would have helped. 

Partially I've opened the issue to document the way to fix it if someone else would use Inkscape to draw the SVGs directly. I think I wouldn't have had this issue if I used e.g. FontForge.

Right now the project works great for me anyway, thank you for that!

**Comment by jeerbl** [comment]
Ok I see.

Though you have to know that this project is just a proxy between Webpack and the [`webfonts-generator`](https://github.com/sunflowerdeath/webfonts-generator) project so I guess this kind of `invalid format` errors should be handled there.

Don't hesitate to open an issue there or make a pull request directly.

Cheers
Jerome

**Comment by ha7ilm** [comment]
OK!
